### ISSUE TITLE
Application audit for sensitive data

### ISSUE THREAD

**Issue by mrteera** [mrteera/web16-06#30]
```
Audit your software for any sensitive data like database passwords 
make sure they are secure. Document the result of your audit and plan.
```

**Comment by mrteera** [comment]
**Audit Check-list**
- [x] Production database credentials

We use environment variables to protect database credentials

```
production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB_NAME'] %>
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
```
- [x] Session ID in `secrets.yml`

Session ID in production is protected by using environment variable:

```
production:
  secret_key_base: <%= ENV["MEJELLY_SECRET_KEY_BASE"] %>
```
- [x] Continuous Integration Credentials
  We protect all credentials on CI using Travis environment variable feature
  ![screen shot 2559-10-12 at 9 19 51 pm](https://cloud.githubusercontent.com/assets/1741387/19313724/bb3672b6-90c1-11e6-9eee-cfbb48bd6195.png)
- [x] Deployment Key
  We protect deployment key using file encryption method, it needs to be decrypted every time CI runs.

```
openssl aes-256-cbc -K $encrypted_b9d256b383d7_key -iv $encrypted_b9d256b383d7_iv -in .travis/web16_deploy_key.enc -out .travis/web16_deploy_key -d
```
